[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# SPA-роутинг (Vue Router history) — все пути на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
